### ISSUE TITLE
LineChart中，x轴是否支持字符串类型？

### ISSUE THREAD

**Issue by inprise1980** [SunPointed/mp_flutter_chart#4]
在LineChart图中，例子中数据是通过List<Entry> values = List();values.add(Entry(x: i.toDouble(), y: val)); 进行数据填充，Entry中，x与y都是double类型，如果x轴要显示字符串，为“1月”、“2月”、“3月”或是时间如“00:00:10”、"00:00:15"之类的，要如何处理？

**Comment by SunPointed** [comment]
LineChartController的参数xAxisSettingFunction中，可以为xAxis设置axisValueFormatter，继承ValueFormatter自己实现getAxisLabel方法
