### ISSUE TITLE
mpAndroidChart通过lineChart.moveViewToX方法移动view到最新数据，mp_flutter_chart要如何实现？

### ISSUE THREAD

**Issue by inprise1980** [SunPointed/mp_flutter_chart#5]
在lineChart中，动态加点，view右移图表到最新数据。在mpAndroidChart中，可以通过lineChart.moveViewToX方法移动，如下
data.addEntry(new Entry(x, y), 0);
data.notifyDataChanged();
lineChart.notifyDataSetChanged();				
lineChart.setVisibleXRangeMaximum(60);
lineChart.moveViewToX(data.getEntryCount());
在mp_flutter_chart中没找到lineChart.moveViewToX的方法，请问要如何实现？

**Comment by SunPointed** [comment]
已经对显示的范围和位置进行了支持，你可以查看demo中的dynamic

**Comment by inprise1980** [comment]
> demo中的dynamic是动态加点，没看到移动，比如我加了30个点，这30个都会显示在当前屏幕，这样数据会挤在一起，而我的需求是想当前屏幕只显示最新10个点（即第20到30的点），而1-20的点移到屏幕左边，不显示在当前屏幕。
> 
> 已经对显示的范围和位置进行了支持，你可以查看demo中的dynamic
